# User credentails to access Twitter API

ACCESS_TOKEN = "4150011698-4PwejyO2pMcDx8WIvTv4tpoqMQzerYziclMM2mz"
ACCESS_TOKEN_SECRET = "iCKokipaPrUUJmL1pqFKdpw9r3vGGh13DRQTaUhFHpxYo"
CONSUMER_API_KEY = "pWpmbOwUKs1Favv7eSFO7DbkV"
CONSUMER_API_SECRET_KEY = "HbAoOeAWQeg3fz64nJA4pdpjkmzy9DMydMCCfWRbbnyYvT5to6"